### ISSUE TITLE
[Bug] Multiple settings window

### ISSUE THREAD

**Issue by rocksdanister** [FireCubeStudios/UnitedSets#7]
Clicking on settings button multiple times will spawn multiple settings window:

![unknown](https://user-images.githubusercontent.com/17554161/197215620-4e5e0a4c-396d-43db-ad55-78a7a0d9019d.png)

**Comment by Get0457** [comment]
The fix is in [this commit](https://github.com/FireCubeStudios/UnitedSets/commit/8ef6604deeafa2f7600496ca870e5952b091635d). The next app update should fix the problem, or you can clone from source to get the latest development version.
